# vim:ts=2:sw=2:et
dist: precise

language: php

php:
  - 5.3

before_install:
  - composer update --dev

script:
  - cd test && wget -q https://raw.github.com/atk14/Atk14/master/src/scripts/run_unit_tests && chmod +x run_unit_tests && ./run_unit_tests
